default_language_version:
  python: python3
default_stages:
  - commit
fail_fast: true
repos:
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.13
  - hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-builtin-literals
      - id: check-toml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
  - hooks:
      - id: check-poetry
    repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
  - hooks:
      - id: python-use-type-annotations
      - id: python-no-log-warn
      - id: python-no-eval
    repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
  - hooks:
      - args:
          - --profile
          - black
          - --filter-files
        id: isort
    repo: https://github.com/pycqa/isort
    rev: 5.9.3
  - hooks:
      - id: black
        args:
          - --safe
          - --quiet
    repo: https://github.com/psf/black
    rev: 21.7b0
  - hooks:
      - id: mypy
        exclude: ^.*test_.*\.py$
        args:
          - --show-error-codes
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
  - hooks:
      - id: flake8
        additional_dependencies:
          - flake8-blind-except
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-isort
          - flake8-polyfill
          - flake8-pytest
          - yesqa
    repo: https://github.com/pycqa/flake8
    rev: 3.9.2
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.2
    hooks:
      - id: bandit
        args:
          - --ini
          - setup.cfg
        exclude: (tests/|scripts/)
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==21.5b2
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: rst-backticks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        stages:
          - commit
  - repo: https://github.com/openstack/bashate
    rev: 2.1.0
    hooks:
      - id: bashate
        args:
          - -i
          - E006
