default_language_version:
  python: python3
default_stages:
- commit
fail_fast: true
repos:
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.17.13
- hooks:
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-builtin-literals
  - id: check-toml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
- hooks:
  - id: check-poetry
  repo: https://gitlab.com/smop/pre-commit-hooks
  rev: v1.0.0
- hooks:
  - id: python-use-type-annotations
  - id: python-no-log-warn
  - id: python-no-eval
  repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
- hooks:
  - args:
    - --profile
    - black
    - --filter-files
    id: isort
  repo: https://github.com/pycqa/isort
  rev: 5.9.3
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 21.7b0
- hooks:
  - id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
- hooks:
  - id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 3.9.2
